# Generated by Django 5.2.4 on 2025-08-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.IntegerField()),
                ('riego', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
